// Code generated by protoc-gen-go. DO NOT EDIT.
// source: assistant.proto

package pluginassistanepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// NoteCommand - note command
type NoteCommand struct {
	// keys
	Keys                 []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoteCommand) Reset()         { *m = NoteCommand{} }
func (m *NoteCommand) String() string { return proto.CompactTextString(m) }
func (*NoteCommand) ProtoMessage()    {}
func (*NoteCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_assistant_005708bff527aa91, []int{0}
}
func (m *NoteCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoteCommand.Unmarshal(m, b)
}
func (m *NoteCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoteCommand.Marshal(b, m, deterministic)
}
func (dst *NoteCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoteCommand.Merge(dst, src)
}
func (m *NoteCommand) XXX_Size() int {
	return xxx_messageInfo_NoteCommand.Size(m)
}
func (m *NoteCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_NoteCommand.DiscardUnknown(m)
}

var xxx_messageInfo_NoteCommand proto.InternalMessageInfo

func (m *NoteCommand) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func init() {
	proto.RegisterType((*NoteCommand)(nil), "pluginassistanepb.NoteCommand")
}

func init() { proto.RegisterFile("assistant.proto", fileDescriptor_assistant_005708bff527aa91) }

var fileDescriptor_assistant_005708bff527aa91 = []byte{
	// 91 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0x2c, 0x2e, 0xce,
	0x2c, 0x2e, 0x49, 0xcc, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x2c, 0xc8, 0x29,
	0x4d, 0xcf, 0xcc, 0x83, 0x09, 0xa7, 0x16, 0x24, 0x29, 0x29, 0x72, 0x71, 0xfb, 0xe5, 0x97, 0xa4,
	0x3a, 0xe7, 0xe7, 0xe6, 0x26, 0xe6, 0xa5, 0x08, 0x09, 0x71, 0xb1, 0x64, 0xa7, 0x56, 0x16, 0x4b,
	0x30, 0x2a, 0x30, 0x6b, 0x70, 0x06, 0x81, 0xd9, 0x49, 0x6c, 0x60, 0xcd, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x82, 0x89, 0xe5, 0x82, 0x4f, 0x00, 0x00, 0x00,
}
