// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dtdata.proto

package plugindtdatapb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// GetDTDataCommand - get dtdata
type GetDTDataCommand struct {
	// mode - mode
	Mode string `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	// startTime - start time
	StartTime string `protobuf:"bytes,2,opt,name=startTime,proto3" json:"startTime,omitempty"`
	// endTime - end time
	EndTime              string   `protobuf:"bytes,3,opt,name=endTime,proto3" json:"endTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDTDataCommand) Reset()         { *m = GetDTDataCommand{} }
func (m *GetDTDataCommand) String() string { return proto.CompactTextString(m) }
func (*GetDTDataCommand) ProtoMessage()    {}
func (*GetDTDataCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_dtdata_039196e787559ece, []int{0}
}
func (m *GetDTDataCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDTDataCommand.Unmarshal(m, b)
}
func (m *GetDTDataCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDTDataCommand.Marshal(b, m, deterministic)
}
func (dst *GetDTDataCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDTDataCommand.Merge(dst, src)
}
func (m *GetDTDataCommand) XXX_Size() int {
	return xxx_messageInfo_GetDTDataCommand.Size(m)
}
func (m *GetDTDataCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDTDataCommand.DiscardUnknown(m)
}

var xxx_messageInfo_GetDTDataCommand proto.InternalMessageInfo

func (m *GetDTDataCommand) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *GetDTDataCommand) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *GetDTDataCommand) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func init() {
	proto.RegisterType((*GetDTDataCommand)(nil), "plugindtdatapb.GetDTDataCommand")
}

func init() { proto.RegisterFile("dtdata.proto", fileDescriptor_dtdata_039196e787559ece) }

var fileDescriptor_dtdata_039196e787559ece = []byte{
	// 124 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x29, 0x49, 0x49,
	0x2c, 0x49, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2b, 0xc8, 0x29, 0x4d, 0xcf, 0xcc,
	0x83, 0x88, 0x15, 0x24, 0x29, 0xc5, 0x71, 0x09, 0xb8, 0xa7, 0x96, 0xb8, 0x84, 0xb8, 0x24, 0x96,
	0x24, 0x3a, 0xe7, 0xe7, 0xe6, 0x26, 0xe6, 0xa5, 0x08, 0x09, 0x71, 0xb1, 0xe4, 0xe6, 0xa7, 0xa4,
	0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x42, 0x32, 0x5c, 0x9c, 0xc5, 0x25, 0x89,
	0x45, 0x25, 0x21, 0x99, 0xb9, 0xa9, 0x12, 0x4c, 0x60, 0x09, 0x84, 0x80, 0x90, 0x04, 0x17, 0x7b,
	0x6a, 0x5e, 0x0a, 0x58, 0x8e, 0x19, 0x2c, 0x07, 0xe3, 0x26, 0xb1, 0x81, 0xad, 0x35, 0x06, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x06, 0xfb, 0xc4, 0xb0, 0x86, 0x00, 0x00, 0x00,
}
