// Code generated by protoc-gen-go. DO NOT EDIT.
// source: translate.proto

package plugintranslatepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// StartTranslateCommand - start translate
type StartTranslateCommand struct {
	Platform             string   `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	SrcLang              string   `protobuf:"bytes,2,opt,name=srcLang,proto3" json:"srcLang,omitempty"`
	DestLang             string   `protobuf:"bytes,3,opt,name=destLang,proto3" json:"destLang,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Userid               string   `protobuf:"bytes,5,opt,name=userid,proto3" json:"userid,omitempty"`
	Retranslate          bool     `protobuf:"varint,6,opt,name=retranslate,proto3" json:"retranslate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartTranslateCommand) Reset()         { *m = StartTranslateCommand{} }
func (m *StartTranslateCommand) String() string { return proto.CompactTextString(m) }
func (*StartTranslateCommand) ProtoMessage()    {}
func (*StartTranslateCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_translate_fbbacf74bf8c38fe, []int{0}
}
func (m *StartTranslateCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartTranslateCommand.Unmarshal(m, b)
}
func (m *StartTranslateCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartTranslateCommand.Marshal(b, m, deterministic)
}
func (dst *StartTranslateCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartTranslateCommand.Merge(dst, src)
}
func (m *StartTranslateCommand) XXX_Size() int {
	return xxx_messageInfo_StartTranslateCommand.Size(m)
}
func (m *StartTranslateCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_StartTranslateCommand.DiscardUnknown(m)
}

var xxx_messageInfo_StartTranslateCommand proto.InternalMessageInfo

func (m *StartTranslateCommand) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *StartTranslateCommand) GetSrcLang() string {
	if m != nil {
		return m.SrcLang
	}
	return ""
}

func (m *StartTranslateCommand) GetDestLang() string {
	if m != nil {
		return m.DestLang
	}
	return ""
}

func (m *StartTranslateCommand) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *StartTranslateCommand) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

func (m *StartTranslateCommand) GetRetranslate() bool {
	if m != nil {
		return m.Retranslate
	}
	return false
}

// StopTranslateCommand - stop translate
type StopTranslateCommand struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Userid               string   `protobuf:"bytes,2,opt,name=userid,proto3" json:"userid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopTranslateCommand) Reset()         { *m = StopTranslateCommand{} }
func (m *StopTranslateCommand) String() string { return proto.CompactTextString(m) }
func (*StopTranslateCommand) ProtoMessage()    {}
func (*StopTranslateCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_translate_fbbacf74bf8c38fe, []int{1}
}
func (m *StopTranslateCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopTranslateCommand.Unmarshal(m, b)
}
func (m *StopTranslateCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopTranslateCommand.Marshal(b, m, deterministic)
}
func (dst *StopTranslateCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopTranslateCommand.Merge(dst, src)
}
func (m *StopTranslateCommand) XXX_Size() int {
	return xxx_messageInfo_StopTranslateCommand.Size(m)
}
func (m *StopTranslateCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_StopTranslateCommand.DiscardUnknown(m)
}

var xxx_messageInfo_StopTranslateCommand proto.InternalMessageInfo

func (m *StopTranslateCommand) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *StopTranslateCommand) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

// TextCommand - text
type TextCommand struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TextCommand) Reset()         { *m = TextCommand{} }
func (m *TextCommand) String() string { return proto.CompactTextString(m) }
func (*TextCommand) ProtoMessage()    {}
func (*TextCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_translate_fbbacf74bf8c38fe, []int{2}
}
func (m *TextCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TextCommand.Unmarshal(m, b)
}
func (m *TextCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TextCommand.Marshal(b, m, deterministic)
}
func (dst *TextCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TextCommand.Merge(dst, src)
}
func (m *TextCommand) XXX_Size() int {
	return xxx_messageInfo_TextCommand.Size(m)
}
func (m *TextCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_TextCommand.DiscardUnknown(m)
}

var xxx_messageInfo_TextCommand proto.InternalMessageInfo

func (m *TextCommand) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*StartTranslateCommand)(nil), "plugintranslatepb.StartTranslateCommand")
	proto.RegisterType((*StopTranslateCommand)(nil), "plugintranslatepb.StopTranslateCommand")
	proto.RegisterType((*TextCommand)(nil), "plugintranslatepb.TextCommand")
}

func init() { proto.RegisterFile("translate.proto", fileDescriptor_translate_fbbacf74bf8c38fe) }

var fileDescriptor_translate_fbbacf74bf8c38fe = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xbd, 0x4e, 0x86, 0x30,
	0x14, 0x86, 0x53, 0x44, 0xc4, 0xc3, 0x60, 0x6c, 0xd4, 0x34, 0x4e, 0xc8, 0xc4, 0xe4, 0xe2, 0x25,
	0xb8, 0x19, 0x27, 0xe0, 0x06, 0x8a, 0x54, 0x42, 0x42, 0x7f, 0xd2, 0x1e, 0x12, 0xee, 0xce, 0x5b,
	0x33, 0x14, 0xda, 0x30, 0x7c, 0xdf, 0x76, 0x9e, 0xf3, 0xe4, 0xed, 0x7b, 0x52, 0x78, 0x40, 0xcb,
	0x95, 0x9b, 0x39, 0x8a, 0x77, 0x63, 0x35, 0x6a, 0xfa, 0x68, 0xe6, 0x65, 0x9c, 0x54, 0x5c, 0x9b,
	0xbe, 0xfa, 0x23, 0xf0, 0xdc, 0x22, 0xb7, 0xd8, 0x85, 0xe5, 0xa7, 0x96, 0x92, 0xab, 0x81, 0xbe,
	0x42, 0x6e, 0x66, 0x8e, 0xbf, 0xda, 0x4a, 0x46, 0x4a, 0x52, 0xdf, 0x37, 0x91, 0x29, 0x83, 0x3b,
	0x67, 0x7f, 0xbe, 0xb9, 0x1a, 0x59, 0xe2, 0x55, 0xc0, 0x2d, 0x35, 0x08, 0x87, 0x5e, 0xdd, 0xec,
	0xa9, 0xc0, 0x9b, 0x5b, 0x9c, 0xb0, 0x8a, 0x4b, 0xc1, 0xd2, 0xdd, 0x05, 0xa6, 0x2f, 0x90, 0x6d,
	0xf3, 0x34, 0xb0, 0x5b, 0x6f, 0x0e, 0xa2, 0x25, 0x14, 0x56, 0xc4, 0x83, 0x59, 0x56, 0x92, 0x3a,
	0x6f, 0xce, 0xab, 0xea, 0x0b, 0x9e, 0x5a, 0xd4, 0xe6, 0xd2, 0xfd, 0xb1, 0x8d, 0x5c, 0x6d, 0x4b,
	0xce, 0x6d, 0xd5, 0x1b, 0x14, 0x9d, 0x58, 0x31, 0x3c, 0x41, 0x21, 0x45, 0xb1, 0xe2, 0x11, 0xf7,
	0x73, 0x9f, 0xf9, 0xaf, 0xfc, 0xf8, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x94, 0x09, 0x8f, 0x09, 0x5d,
	0x01, 0x00, 0x00,
}
