// Code generated by protoc-gen-go. DO NOT EDIT.
// source: translate.proto

package plugintranslatepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// StartTranslateCommand - start translate
type StartTranslateCommand struct {
	Platform             string   `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	SrcLang              string   `protobuf:"bytes,2,opt,name=srcLang,proto3" json:"srcLang,omitempty"`
	DestLang             string   `protobuf:"bytes,3,opt,name=destLang,proto3" json:"destLang,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartTranslateCommand) Reset()         { *m = StartTranslateCommand{} }
func (m *StartTranslateCommand) String() string { return proto.CompactTextString(m) }
func (*StartTranslateCommand) ProtoMessage()    {}
func (*StartTranslateCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_translate_1b0a44f289ff52a4, []int{0}
}
func (m *StartTranslateCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartTranslateCommand.Unmarshal(m, b)
}
func (m *StartTranslateCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartTranslateCommand.Marshal(b, m, deterministic)
}
func (dst *StartTranslateCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartTranslateCommand.Merge(dst, src)
}
func (m *StartTranslateCommand) XXX_Size() int {
	return xxx_messageInfo_StartTranslateCommand.Size(m)
}
func (m *StartTranslateCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_StartTranslateCommand.DiscardUnknown(m)
}

var xxx_messageInfo_StartTranslateCommand proto.InternalMessageInfo

func (m *StartTranslateCommand) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *StartTranslateCommand) GetSrcLang() string {
	if m != nil {
		return m.SrcLang
	}
	return ""
}

func (m *StartTranslateCommand) GetDestLang() string {
	if m != nil {
		return m.DestLang
	}
	return ""
}

// StopTranslateCommand - stop translate
type StopTranslateCommand struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopTranslateCommand) Reset()         { *m = StopTranslateCommand{} }
func (m *StopTranslateCommand) String() string { return proto.CompactTextString(m) }
func (*StopTranslateCommand) ProtoMessage()    {}
func (*StopTranslateCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_translate_1b0a44f289ff52a4, []int{1}
}
func (m *StopTranslateCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopTranslateCommand.Unmarshal(m, b)
}
func (m *StopTranslateCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopTranslateCommand.Marshal(b, m, deterministic)
}
func (dst *StopTranslateCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopTranslateCommand.Merge(dst, src)
}
func (m *StopTranslateCommand) XXX_Size() int {
	return xxx_messageInfo_StopTranslateCommand.Size(m)
}
func (m *StopTranslateCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_StopTranslateCommand.DiscardUnknown(m)
}

var xxx_messageInfo_StopTranslateCommand proto.InternalMessageInfo

// TextCommand - text
type TextCommand struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TextCommand) Reset()         { *m = TextCommand{} }
func (m *TextCommand) String() string { return proto.CompactTextString(m) }
func (*TextCommand) ProtoMessage()    {}
func (*TextCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_translate_1b0a44f289ff52a4, []int{2}
}
func (m *TextCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TextCommand.Unmarshal(m, b)
}
func (m *TextCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TextCommand.Marshal(b, m, deterministic)
}
func (dst *TextCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TextCommand.Merge(dst, src)
}
func (m *TextCommand) XXX_Size() int {
	return xxx_messageInfo_TextCommand.Size(m)
}
func (m *TextCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_TextCommand.DiscardUnknown(m)
}

var xxx_messageInfo_TextCommand proto.InternalMessageInfo

func (m *TextCommand) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*StartTranslateCommand)(nil), "plugintranslatepb.StartTranslateCommand")
	proto.RegisterType((*StopTranslateCommand)(nil), "plugintranslatepb.StopTranslateCommand")
	proto.RegisterType((*TextCommand)(nil), "plugintranslatepb.TextCommand")
}

func init() { proto.RegisterFile("translate.proto", fileDescriptor_translate_1b0a44f289ff52a4) }

var fileDescriptor_translate_1b0a44f289ff52a4 = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x29, 0x4a, 0xcc,
	0x2b, 0xce, 0x49, 0x2c, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x2c, 0xc8, 0x29,
	0x4d, 0xcf, 0xcc, 0x83, 0x0b, 0x17, 0x24, 0x29, 0x65, 0x72, 0x89, 0x06, 0x97, 0x24, 0x16, 0x95,
	0x84, 0xc0, 0xc4, 0x9c, 0xf3, 0x73, 0x73, 0x13, 0xf3, 0x52, 0x84, 0xa4, 0xb8, 0x38, 0x0a, 0x72,
	0x12, 0x4b, 0xd2, 0xf2, 0x8b, 0x72, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xe0, 0x7c, 0x21,
	0x09, 0x2e, 0xf6, 0xe2, 0xa2, 0x64, 0x9f, 0xc4, 0xbc, 0x74, 0x09, 0x26, 0xb0, 0x14, 0x8c, 0x0b,
	0xd2, 0x95, 0x92, 0x5a, 0x5c, 0x02, 0x96, 0x62, 0x86, 0xe8, 0x82, 0xf1, 0x95, 0xc4, 0xb8, 0x44,
	0x82, 0x4b, 0xf2, 0x0b, 0xd0, 0x6d, 0x52, 0x52, 0xe4, 0xe2, 0x0e, 0x49, 0xad, 0x28, 0x81, 0x59,
	0x2c, 0xc4, 0xc5, 0x52, 0x92, 0x5a, 0x51, 0x02, 0xb5, 0x14, 0xcc, 0x4e, 0x62, 0x03, 0xbb, 0xdf,
	0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x44, 0xb1, 0xf6, 0x38, 0xd2, 0x00, 0x00, 0x00,
}
