// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notekeyword.proto

package pluginnotekeywordpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// NoteKeywordCommand - note keyword command
type NoteKeywordCommand struct {
	// keyword - keyword
	Keyword              string   `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoteKeywordCommand) Reset()         { *m = NoteKeywordCommand{} }
func (m *NoteKeywordCommand) String() string { return proto.CompactTextString(m) }
func (*NoteKeywordCommand) ProtoMessage()    {}
func (*NoteKeywordCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_notekeyword_e32deb9b32b4b32e, []int{0}
}
func (m *NoteKeywordCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoteKeywordCommand.Unmarshal(m, b)
}
func (m *NoteKeywordCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoteKeywordCommand.Marshal(b, m, deterministic)
}
func (dst *NoteKeywordCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoteKeywordCommand.Merge(dst, src)
}
func (m *NoteKeywordCommand) XXX_Size() int {
	return xxx_messageInfo_NoteKeywordCommand.Size(m)
}
func (m *NoteKeywordCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_NoteKeywordCommand.DiscardUnknown(m)
}

var xxx_messageInfo_NoteKeywordCommand proto.InternalMessageInfo

func (m *NoteKeywordCommand) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func init() {
	proto.RegisterType((*NoteKeywordCommand)(nil), "pluginnotekeywordpb.NoteKeywordCommand")
}

func init() { proto.RegisterFile("notekeyword.proto", fileDescriptor_notekeyword_e32deb9b32b4b32e) }

var fileDescriptor_notekeyword_e32deb9b32b4b32e = []byte{
	// 93 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcc, 0xcb, 0x2f, 0x49,
	0xcd, 0x4e, 0xad, 0x2c, 0xcf, 0x2f, 0x4a, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x2e,
	0xc8, 0x29, 0x4d, 0xcf, 0xcc, 0x43, 0x92, 0x28, 0x48, 0x52, 0xd2, 0xe3, 0x12, 0xf2, 0xcb, 0x2f,
	0x49, 0xf5, 0x86, 0x08, 0x38, 0xe7, 0xe7, 0xe6, 0x26, 0xe6, 0xa5, 0x08, 0x49, 0x70, 0xb1, 0x43,
	0x95, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xc1, 0xb8, 0x49, 0x6c, 0x60, 0xb3, 0x8c, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x38, 0xfe, 0x38, 0xac, 0x60, 0x00, 0x00, 0x00,
}
