// Code generated by protoc-gen-go. DO NOT EDIT.
// source: generatepwd.proto

package plugingeneratepwdpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// GeneratePassword - generate password
type GeneratePassword struct {
	// length - length
	Length int32 `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	// mode - mode
	Mode                 string   `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneratePassword) Reset()         { *m = GeneratePassword{} }
func (m *GeneratePassword) String() string { return proto.CompactTextString(m) }
func (*GeneratePassword) ProtoMessage()    {}
func (*GeneratePassword) Descriptor() ([]byte, []int) {
	return fileDescriptor_generatepwd_d91b26debb7615d2, []int{0}
}
func (m *GeneratePassword) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneratePassword.Unmarshal(m, b)
}
func (m *GeneratePassword) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneratePassword.Marshal(b, m, deterministic)
}
func (dst *GeneratePassword) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneratePassword.Merge(dst, src)
}
func (m *GeneratePassword) XXX_Size() int {
	return xxx_messageInfo_GeneratePassword.Size(m)
}
func (m *GeneratePassword) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneratePassword.DiscardUnknown(m)
}

var xxx_messageInfo_GeneratePassword proto.InternalMessageInfo

func (m *GeneratePassword) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *GeneratePassword) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func init() {
	proto.RegisterType((*GeneratePassword)(nil), "plugingeneratepwdpb.GeneratePassword")
}

func init() { proto.RegisterFile("generatepwd.proto", fileDescriptor_generatepwd_d91b26debb7615d2) }

var fileDescriptor_generatepwd_d91b26debb7615d2 = []byte{
	// 111 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0x4f, 0xcd, 0x4b,
	0x2d, 0x4a, 0x2c, 0x49, 0x2d, 0x28, 0x4f, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x2e,
	0xc8, 0x29, 0x4d, 0xcf, 0xcc, 0x43, 0x92, 0x28, 0x48, 0x52, 0xb2, 0xe3, 0x12, 0x70, 0x87, 0x0a,
	0x04, 0x24, 0x16, 0x17, 0x97, 0xe7, 0x17, 0xa5, 0x08, 0x89, 0x71, 0xb1, 0xe5, 0xa4, 0xe6, 0xa5,
	0x97, 0x64, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x41, 0x79, 0x42, 0x42, 0x5c, 0x2c, 0xb9,
	0xf9, 0x29, 0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0x76, 0x12, 0x1b, 0xd8, 0x6c,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x44, 0x6e, 0x17, 0x33, 0x70, 0x00, 0x00, 0x00,
}
