// Code generated by protoc-gen-go. DO NOT EDIT.
// source: jarvisnodeex.proto

package pluginjarvisnodeexpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FileData struct {
	// filename - filename
	Filename string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	// data - file data with bytes
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// fileType - file type
	FileType string `protobuf:"bytes,3,opt,name=fileType,proto3" json:"fileType,omitempty"`
	// fullPath - full path
	FullPath             string   `protobuf:"bytes,4,opt,name=fullPath,proto3" json:"fullPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileData) Reset()         { *m = FileData{} }
func (m *FileData) String() string { return proto.CompactTextString(m) }
func (*FileData) ProtoMessage()    {}
func (*FileData) Descriptor() ([]byte, []int) {
	return fileDescriptor_jarvisnodeex_ea51596d174ba073, []int{0}
}
func (m *FileData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileData.Unmarshal(m, b)
}
func (m *FileData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileData.Marshal(b, m, deterministic)
}
func (dst *FileData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileData.Merge(dst, src)
}
func (m *FileData) XXX_Size() int {
	return xxx_messageInfo_FileData.Size(m)
}
func (m *FileData) XXX_DiscardUnknown() {
	xxx_messageInfo_FileData.DiscardUnknown(m)
}

var xxx_messageInfo_FileData proto.InternalMessageInfo

func (m *FileData) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *FileData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *FileData) GetFileType() string {
	if m != nil {
		return m.FileType
	}
	return ""
}

func (m *FileData) GetFullPath() string {
	if m != nil {
		return m.FullPath
	}
	return ""
}

// RunScriptCommand - run script command
type RunScriptCommand struct {
	// jarvisNodeName - jarvisnode name
	JarvisNodeName string `protobuf:"bytes,1,opt,name=jarvisNodeName,proto3" json:"jarvisNodeName,omitempty"`
	// destGlobPatterns - when finished script, will get these files.
	DestGlobPatterns []string `protobuf:"bytes,2,rep,name=destGlobPatterns,proto3" json:"destGlobPatterns,omitempty"`
	// scriptFile - script file
	ScriptFile *FileData `protobuf:"bytes,3,opt,name=scriptFile,proto3" json:"scriptFile,omitempty"`
	// files - files
	Files                []*FileData `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RunScriptCommand) Reset()         { *m = RunScriptCommand{} }
func (m *RunScriptCommand) String() string { return proto.CompactTextString(m) }
func (*RunScriptCommand) ProtoMessage()    {}
func (*RunScriptCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_jarvisnodeex_ea51596d174ba073, []int{1}
}
func (m *RunScriptCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunScriptCommand.Unmarshal(m, b)
}
func (m *RunScriptCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunScriptCommand.Marshal(b, m, deterministic)
}
func (dst *RunScriptCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunScriptCommand.Merge(dst, src)
}
func (m *RunScriptCommand) XXX_Size() int {
	return xxx_messageInfo_RunScriptCommand.Size(m)
}
func (m *RunScriptCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_RunScriptCommand.DiscardUnknown(m)
}

var xxx_messageInfo_RunScriptCommand proto.InternalMessageInfo

func (m *RunScriptCommand) GetJarvisNodeName() string {
	if m != nil {
		return m.JarvisNodeName
	}
	return ""
}

func (m *RunScriptCommand) GetDestGlobPatterns() []string {
	if m != nil {
		return m.DestGlobPatterns
	}
	return nil
}

func (m *RunScriptCommand) GetScriptFile() *FileData {
	if m != nil {
		return m.ScriptFile
	}
	return nil
}

func (m *RunScriptCommand) GetFiles() []*FileData {
	if m != nil {
		return m.Files
	}
	return nil
}

// PluginData - plugin data
type PluginData struct {
	RunScript            *RunScriptCommand `protobuf:"bytes,1,opt,name=runScript,proto3" json:"runScript,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PluginData) Reset()         { *m = PluginData{} }
func (m *PluginData) String() string { return proto.CompactTextString(m) }
func (*PluginData) ProtoMessage()    {}
func (*PluginData) Descriptor() ([]byte, []int) {
	return fileDescriptor_jarvisnodeex_ea51596d174ba073, []int{2}
}
func (m *PluginData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PluginData.Unmarshal(m, b)
}
func (m *PluginData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PluginData.Marshal(b, m, deterministic)
}
func (dst *PluginData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PluginData.Merge(dst, src)
}
func (m *PluginData) XXX_Size() int {
	return xxx_messageInfo_PluginData.Size(m)
}
func (m *PluginData) XXX_DiscardUnknown() {
	xxx_messageInfo_PluginData.DiscardUnknown(m)
}

var xxx_messageInfo_PluginData proto.InternalMessageInfo

func (m *PluginData) GetRunScript() *RunScriptCommand {
	if m != nil {
		return m.RunScript
	}
	return nil
}

// UpdNodesCommand - updnodes command
type UpdNodesCommand struct {
	// nodeType - jarvisnode type name
	NodeType string `protobuf:"bytes,1,opt,name=nodeType,proto3" json:"nodeType,omitempty"`
	// nodeTypeVer - new version
	NodeTypeVer          string   `protobuf:"bytes,2,opt,name=nodeTypeVer,proto3" json:"nodeTypeVer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdNodesCommand) Reset()         { *m = UpdNodesCommand{} }
func (m *UpdNodesCommand) String() string { return proto.CompactTextString(m) }
func (*UpdNodesCommand) ProtoMessage()    {}
func (*UpdNodesCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_jarvisnodeex_ea51596d174ba073, []int{3}
}
func (m *UpdNodesCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdNodesCommand.Unmarshal(m, b)
}
func (m *UpdNodesCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdNodesCommand.Marshal(b, m, deterministic)
}
func (dst *UpdNodesCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdNodesCommand.Merge(dst, src)
}
func (m *UpdNodesCommand) XXX_Size() int {
	return xxx_messageInfo_UpdNodesCommand.Size(m)
}
func (m *UpdNodesCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdNodesCommand.DiscardUnknown(m)
}

var xxx_messageInfo_UpdNodesCommand proto.InternalMessageInfo

func (m *UpdNodesCommand) GetNodeType() string {
	if m != nil {
		return m.NodeType
	}
	return ""
}

func (m *UpdNodesCommand) GetNodeTypeVer() string {
	if m != nil {
		return m.NodeTypeVer
	}
	return ""
}

func init() {
	proto.RegisterType((*FileData)(nil), "pluginjarvisnodeexpb.FileData")
	proto.RegisterType((*RunScriptCommand)(nil), "pluginjarvisnodeexpb.RunScriptCommand")
	proto.RegisterType((*PluginData)(nil), "pluginjarvisnodeexpb.PluginData")
	proto.RegisterType((*UpdNodesCommand)(nil), "pluginjarvisnodeexpb.UpdNodesCommand")
}

func init() { proto.RegisterFile("jarvisnodeex.proto", fileDescriptor_jarvisnodeex_ea51596d174ba073) }

var fileDescriptor_jarvisnodeex_ea51596d174ba073 = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x55, 0xda, 0x82, 0x9a, 0x2b, 0x82, 0xca, 0x62, 0xb0, 0x3a, 0xa0, 0x28, 0x43, 0x15, 0x31,
	0x64, 0x28, 0xcc, 0x2c, 0x54, 0xb0, 0x95, 0xc8, 0x7c, 0xec, 0x0e, 0x36, 0x10, 0xe4, 0xd8, 0x96,
	0xed, 0x20, 0xf8, 0xaf, 0xfc, 0x18, 0x14, 0x37, 0x26, 0x51, 0xe9, 0xc0, 0x76, 0xef, 0xee, 0xbd,
	0xe4, 0xde, 0x3b, 0x03, 0x7a, 0xa7, 0xe6, 0xa3, 0xb2, 0x52, 0x31, 0xce, 0x3f, 0x73, 0x6d, 0x94,
	0x53, 0xe8, 0x54, 0x8b, 0xe6, 0xb5, 0x92, 0xc3, 0x89, 0x2e, 0x53, 0x03, 0xd3, 0x9b, 0x4a, 0xf0,
	0x35, 0x75, 0x14, 0x2d, 0x60, 0xfa, 0x52, 0x09, 0x2e, 0x69, 0xcd, 0x71, 0x94, 0x44, 0x59, 0x4c,
	0x7e, 0x31, 0x42, 0x30, 0x61, 0xd4, 0x51, 0x3c, 0x4a, 0xa2, 0xec, 0x88, 0xf8, 0x3a, 0xf0, 0x1f,
	0xbe, 0x34, 0xc7, 0xe3, 0x9e, 0xdf, 0x62, 0x3f, 0x6b, 0x84, 0x28, 0xa8, 0x7b, 0xc3, 0x93, 0x6e,
	0xd6, 0xe1, 0xf4, 0x3b, 0x82, 0x39, 0x69, 0xe4, 0xfd, 0xb3, 0xa9, 0xb4, 0xbb, 0x56, 0x75, 0x4d,
	0x25, 0x43, 0x4b, 0x38, 0xde, 0xae, 0xb6, 0x51, 0x8c, 0x6f, 0xfa, 0x15, 0x76, 0xba, 0xe8, 0x1c,
	0xe6, 0x8c, 0x5b, 0x77, 0x2b, 0x54, 0x59, 0x50, 0xe7, 0xb8, 0x91, 0x16, 0x8f, 0x92, 0x71, 0x16,
	0x93, 0x3f, 0x7d, 0x74, 0x05, 0x60, 0xfd, 0x4f, 0x5a, 0x8b, 0x7e, 0xc5, 0xd9, 0xea, 0x2c, 0xdf,
	0x97, 0x43, 0x1e, 0x42, 0x20, 0x03, 0x05, 0xba, 0x84, 0x83, 0xd6, 0x90, 0xc5, 0x93, 0x64, 0xfc,
	0x0f, 0xe9, 0x96, 0x9c, 0x12, 0x80, 0xc2, 0xf3, 0x7c, 0xa8, 0x6b, 0x88, 0x4d, 0xf0, 0xea, 0x2d,
	0xcd, 0x56, 0xcb, 0xfd, 0xdf, 0xd9, 0x8d, 0x84, 0xf4, 0xc2, 0xf4, 0x0e, 0x4e, 0x1e, 0x35, 0x6b,
	0x43, 0xb0, 0x21, 0xb0, 0x05, 0x4c, 0x5b, 0xa9, 0x4f, 0xbf, 0xbb, 0x56, 0xc0, 0x28, 0x81, 0x59,
	0xa8, 0x9f, 0xb8, 0xf1, 0x47, 0x8b, 0xc9, 0xb0, 0x55, 0x1e, 0xfa, 0x47, 0x71, 0xf1, 0x13, 0x00,
	0x00, 0xff, 0xff, 0x6e, 0x54, 0x20, 0x26, 0x2a, 0x02, 0x00, 0x00,
}
