// Code generated by protoc-gen-go. DO NOT EDIT.
// source: duckling.proto

package pluginducklingpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// RequestDuckling - request duckling
type RequestDuckling struct {
	// lang - lang
	Lang string `protobuf:"bytes,1,opt,name=lang,proto3" json:"lang,omitempty"`
	// text - text
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestDuckling) Reset()         { *m = RequestDuckling{} }
func (m *RequestDuckling) String() string { return proto.CompactTextString(m) }
func (*RequestDuckling) ProtoMessage()    {}
func (*RequestDuckling) Descriptor() ([]byte, []int) {
	return fileDescriptor_duckling_f252062694bcd186, []int{0}
}
func (m *RequestDuckling) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestDuckling.Unmarshal(m, b)
}
func (m *RequestDuckling) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestDuckling.Marshal(b, m, deterministic)
}
func (dst *RequestDuckling) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestDuckling.Merge(dst, src)
}
func (m *RequestDuckling) XXX_Size() int {
	return xxx_messageInfo_RequestDuckling.Size(m)
}
func (m *RequestDuckling) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestDuckling.DiscardUnknown(m)
}

var xxx_messageInfo_RequestDuckling proto.InternalMessageInfo

func (m *RequestDuckling) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

func (m *RequestDuckling) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestDuckling)(nil), "pluginducklingpb.RequestDuckling")
}

func init() { proto.RegisterFile("duckling.proto", fileDescriptor_duckling_f252062694bcd186) }

var fileDescriptor_duckling_f252062694bcd186 = []byte{
	// 99 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x29, 0x4d, 0xce,
	0xce, 0xc9, 0xcc, 0x4b, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x28, 0xc8, 0x29, 0x4d,
	0xcf, 0xcc, 0x83, 0x89, 0x16, 0x24, 0x29, 0x59, 0x72, 0xf1, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16,
	0x97, 0xb8, 0x40, 0x05, 0x85, 0x84, 0xb8, 0x58, 0x72, 0x12, 0xf3, 0xd2, 0x25, 0x18, 0x15, 0x18,
	0x35, 0x38, 0x83, 0xc0, 0x6c, 0x90, 0x58, 0x49, 0x6a, 0x45, 0x89, 0x04, 0x13, 0x44, 0x0c, 0xc4,
	0x4e, 0x62, 0x03, 0x9b, 0x69, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x96, 0xe7, 0xc6, 0x65,
	0x00, 0x00, 0x00,
}
