// Code generated by protoc-gen-go. DO NOT EDIT.
// source: assistant.proto

package assistantdbpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Note struct {
	NoteID               int64    `protobuf:"varint,1,opt,name=noteID,proto3" json:"noteID,omitempty"`
	Data                 []string `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	Keys                 []string `protobuf:"bytes,3,rep,name=keys,proto3" json:"keys,omitempty"`
	CreateTime           int64    `protobuf:"varint,4,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime           int64    `protobuf:"varint,5,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Note) Reset()         { *m = Note{} }
func (m *Note) String() string { return proto.CompactTextString(m) }
func (*Note) ProtoMessage()    {}
func (*Note) Descriptor() ([]byte, []int) {
	return fileDescriptor_assistant_9c0aa789342717a1, []int{0}
}
func (m *Note) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Note.Unmarshal(m, b)
}
func (m *Note) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Note.Marshal(b, m, deterministic)
}
func (dst *Note) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Note.Merge(dst, src)
}
func (m *Note) XXX_Size() int {
	return xxx_messageInfo_Note.Size(m)
}
func (m *Note) XXX_DiscardUnknown() {
	xxx_messageInfo_Note.DiscardUnknown(m)
}

var xxx_messageInfo_Note proto.InternalMessageInfo

func (m *Note) GetNoteID() int64 {
	if m != nil {
		return m.NoteID
	}
	return 0
}

func (m *Note) GetData() []string {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Note) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *Note) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Note) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

type KeyInfo struct {
	NoteIDs              []int64  `protobuf:"varint,1,rep,packed,name=noteIDs,proto3" json:"noteIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyInfo) Reset()         { *m = KeyInfo{} }
func (m *KeyInfo) String() string { return proto.CompactTextString(m) }
func (*KeyInfo) ProtoMessage()    {}
func (*KeyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_assistant_9c0aa789342717a1, []int{1}
}
func (m *KeyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyInfo.Unmarshal(m, b)
}
func (m *KeyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyInfo.Marshal(b, m, deterministic)
}
func (dst *KeyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyInfo.Merge(dst, src)
}
func (m *KeyInfo) XXX_Size() int {
	return xxx_messageInfo_KeyInfo.Size(m)
}
func (m *KeyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_KeyInfo proto.InternalMessageInfo

func (m *KeyInfo) GetNoteIDs() []int64 {
	if m != nil {
		return m.NoteIDs
	}
	return nil
}

type UserAssistantInfo struct {
	MaxNoteID            int64    `protobuf:"varint,1,opt,name=maxNoteID,proto3" json:"maxNoteID,omitempty"`
	Keys                 []string `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserAssistantInfo) Reset()         { *m = UserAssistantInfo{} }
func (m *UserAssistantInfo) String() string { return proto.CompactTextString(m) }
func (*UserAssistantInfo) ProtoMessage()    {}
func (*UserAssistantInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_assistant_9c0aa789342717a1, []int{2}
}
func (m *UserAssistantInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAssistantInfo.Unmarshal(m, b)
}
func (m *UserAssistantInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAssistantInfo.Marshal(b, m, deterministic)
}
func (dst *UserAssistantInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAssistantInfo.Merge(dst, src)
}
func (m *UserAssistantInfo) XXX_Size() int {
	return xxx_messageInfo_UserAssistantInfo.Size(m)
}
func (m *UserAssistantInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAssistantInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserAssistantInfo proto.InternalMessageInfo

func (m *UserAssistantInfo) GetMaxNoteID() int64 {
	if m != nil {
		return m.MaxNoteID
	}
	return 0
}

func (m *UserAssistantInfo) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func init() {
	proto.RegisterType((*Note)(nil), "assistantdbpb.Note")
	proto.RegisterType((*KeyInfo)(nil), "assistantdbpb.KeyInfo")
	proto.RegisterType((*UserAssistantInfo)(nil), "assistantdbpb.UserAssistantInfo")
}

func init() { proto.RegisterFile("assistant.proto", fileDescriptor_assistant_9c0aa789342717a1) }

var fileDescriptor_assistant_9c0aa789342717a1 = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0x2c, 0x2e, 0xce,
	0x2c, 0x2e, 0x49, 0xcc, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x85, 0x0b, 0xa4,
	0x24, 0x15, 0x24, 0x29, 0xb5, 0x31, 0x72, 0xb1, 0xf8, 0xe5, 0x97, 0xa4, 0x0a, 0x89, 0x71, 0xb1,
	0xe5, 0xe5, 0x97, 0xa4, 0x7a, 0xba, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x07, 0x41, 0x79, 0x42,
	0x42, 0x5c, 0x2c, 0x29, 0x89, 0x25, 0x89, 0x12, 0x4c, 0x0a, 0xcc, 0x1a, 0x9c, 0x41, 0x60, 0x36,
	0x48, 0x2c, 0x3b, 0xb5, 0xb2, 0x58, 0x82, 0x19, 0x22, 0x06, 0x62, 0x0b, 0xc9, 0x71, 0x71, 0x25,
	0x17, 0xa5, 0x26, 0x96, 0xa4, 0x86, 0x64, 0xe6, 0xa6, 0x4a, 0xb0, 0x80, 0xcd, 0x40, 0x12, 0x01,
	0xc9, 0x97, 0x16, 0xa4, 0xc0, 0xe4, 0x59, 0x21, 0xf2, 0x08, 0x11, 0x25, 0x65, 0x2e, 0x76, 0xef,
	0xd4, 0x4a, 0xcf, 0xbc, 0xb4, 0x7c, 0x21, 0x09, 0x2e, 0x76, 0x88, 0xe5, 0xc5, 0x12, 0x8c, 0x0a,
	0xcc, 0x1a, 0xcc, 0x41, 0x30, 0xae, 0x92, 0x2b, 0x97, 0x60, 0x68, 0x71, 0x6a, 0x91, 0x23, 0xcc,
	0x0b, 0x60, 0xe5, 0x32, 0x5c, 0x9c, 0xb9, 0x89, 0x15, 0x7e, 0xc8, 0x8e, 0x47, 0x08, 0xc0, 0xdd,
	0xca, 0x84, 0x70, 0x6b, 0x12, 0x1b, 0x38, 0x28, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x26,
	0x0b, 0xff, 0xdd, 0x1d, 0x01, 0x00, 0x00,
}
