// Code generated by protoc-gen-go. DO NOT EDIT.
// source: jarvisnode.proto

package pluginjarvisnodepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// NodesCommand - nodes command
type NodesCommand struct {
	// nums - show node nums
	Nums                 int32    `protobuf:"varint,1,opt,name=nums,proto3" json:"nums,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodesCommand) Reset()         { *m = NodesCommand{} }
func (m *NodesCommand) String() string { return proto.CompactTextString(m) }
func (*NodesCommand) ProtoMessage()    {}
func (*NodesCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_jarvisnode_0a8e9cd57a5317de, []int{0}
}
func (m *NodesCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodesCommand.Unmarshal(m, b)
}
func (m *NodesCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodesCommand.Marshal(b, m, deterministic)
}
func (dst *NodesCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodesCommand.Merge(dst, src)
}
func (m *NodesCommand) XXX_Size() int {
	return xxx_messageInfo_NodesCommand.Size(m)
}
func (m *NodesCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_NodesCommand.DiscardUnknown(m)
}

var xxx_messageInfo_NodesCommand proto.InternalMessageInfo

func (m *NodesCommand) GetNums() int32 {
	if m != nil {
		return m.Nums
	}
	return 0
}

// RequestFileCommand - request file command
type RequestFileCommand struct {
	// jarvisNodeName - jarvisnode name
	JarvisNodeName string `protobuf:"bytes,1,opt,name=jarvisNodeName,proto3" json:"jarvisNodeName,omitempty"`
	// fileFullPath - file fullpath
	FileFullPath         string   `protobuf:"bytes,2,opt,name=fileFullPath,proto3" json:"fileFullPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestFileCommand) Reset()         { *m = RequestFileCommand{} }
func (m *RequestFileCommand) String() string { return proto.CompactTextString(m) }
func (*RequestFileCommand) ProtoMessage()    {}
func (*RequestFileCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_jarvisnode_0a8e9cd57a5317de, []int{1}
}
func (m *RequestFileCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestFileCommand.Unmarshal(m, b)
}
func (m *RequestFileCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestFileCommand.Marshal(b, m, deterministic)
}
func (dst *RequestFileCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestFileCommand.Merge(dst, src)
}
func (m *RequestFileCommand) XXX_Size() int {
	return xxx_messageInfo_RequestFileCommand.Size(m)
}
func (m *RequestFileCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestFileCommand.DiscardUnknown(m)
}

var xxx_messageInfo_RequestFileCommand proto.InternalMessageInfo

func (m *RequestFileCommand) GetJarvisNodeName() string {
	if m != nil {
		return m.JarvisNodeName
	}
	return ""
}

func (m *RequestFileCommand) GetFileFullPath() string {
	if m != nil {
		return m.FileFullPath
	}
	return ""
}

func init() {
	proto.RegisterType((*NodesCommand)(nil), "pluginjarvisnodepb.NodesCommand")
	proto.RegisterType((*RequestFileCommand)(nil), "pluginjarvisnodepb.RequestFileCommand")
}

func init() { proto.RegisterFile("jarvisnode.proto", fileDescriptor_jarvisnode_0a8e9cd57a5317de) }

var fileDescriptor_jarvisnode_0a8e9cd57a5317de = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc8, 0x4a, 0x2c, 0x2a,
	0xcb, 0x2c, 0xce, 0xcb, 0x4f, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x2a, 0xc8,
	0x29, 0x4d, 0xcf, 0xcc, 0x43, 0x88, 0x17, 0x24, 0x29, 0x29, 0x71, 0xf1, 0xf8, 0xe5, 0xa7, 0xa4,
	0x16, 0x3b, 0xe7, 0xe7, 0xe6, 0x26, 0xe6, 0xa5, 0x08, 0x09, 0x71, 0xb1, 0xe4, 0x95, 0xe6, 0x16,
	0x4b, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x81, 0xd9, 0x4a, 0x09, 0x5c, 0x42, 0x41, 0xa9, 0x85,
	0xa5, 0xa9, 0xc5, 0x25, 0x6e, 0x99, 0x39, 0xa9, 0x30, 0x95, 0x6a, 0x5c, 0x7c, 0x10, 0x93, 0x40,
	0xfa, 0xfd, 0x12, 0x73, 0x53, 0xc1, 0x7a, 0x38, 0x83, 0xd0, 0x44, 0x85, 0x94, 0xb8, 0x78, 0xd2,
	0x32, 0x73, 0x52, 0xdd, 0x4a, 0x73, 0x72, 0x02, 0x12, 0x4b, 0x32, 0x24, 0x98, 0xc0, 0xaa, 0x50,
	0xc4, 0x92, 0xd8, 0xc0, 0x0e, 0x34, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x00, 0x4d, 0x7b, 0xc1,
	0xb4, 0x00, 0x00, 0x00,
}
