// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chatbotdb.proto

package chatbotdbpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	NickName             string   `protobuf:"bytes,1,opt,name=nickName,proto3" json:"nickName,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	UserName             string   `protobuf:"bytes,3,opt,name=userName,proto3" json:"userName,omitempty"`
	LastMsgID            int64    `protobuf:"varint,4,opt,name=lastMsgID,proto3" json:"lastMsgID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_chatbotdb_ca749060f8cacc4e, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *User) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *User) GetLastMsgID() int64 {
	if m != nil {
		return m.LastMsgID
	}
	return 0
}

type Message struct {
	ChatID               string   `protobuf:"bytes,1,opt,name=chatID,proto3" json:"chatID,omitempty"`
	From                 *User    `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   *User    `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Text                 string   `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	TimeStamp            int64    `protobuf:"varint,5,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	MsgID                string   `protobuf:"bytes,6,opt,name=msgID,proto3" json:"msgID,omitempty"`
	Options              []string `protobuf:"bytes,7,rep,name=options,proto3" json:"options,omitempty"`
	Selected             int32    `protobuf:"varint,8,opt,name=selected,proto3" json:"selected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_chatbotdb_ca749060f8cacc4e, []int{1}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetChatID() string {
	if m != nil {
		return m.ChatID
	}
	return ""
}

func (m *Message) GetFrom() *User {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Message) GetTo() *User {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Message) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *Message) GetMsgID() string {
	if m != nil {
		return m.MsgID
	}
	return ""
}

func (m *Message) GetOptions() []string {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *Message) GetSelected() int32 {
	if m != nil {
		return m.Selected
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "chatbotdbpb.User")
	proto.RegisterType((*Message)(nil), "chatbotdbpb.Message")
}

func init() { proto.RegisterFile("chatbotdb.proto", fileDescriptor_chatbotdb_ca749060f8cacc4e) }

var fileDescriptor_chatbotdb_ca749060f8cacc4e = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x3f, 0x4e, 0xec, 0x30,
	0x10, 0x87, 0xe5, 0xfc, 0xdd, 0xcc, 0x16, 0x4f, 0x6f, 0x84, 0x90, 0x85, 0x28, 0xc2, 0x4a, 0x48,
	0xa9, 0x52, 0xc0, 0x15, 0xd2, 0xa4, 0x58, 0x0a, 0x23, 0x0e, 0xe0, 0x64, 0xcd, 0x12, 0xb1, 0x5e,
	0x47, 0xf1, 0x20, 0x71, 0x65, 0x6e, 0x81, 0x3c, 0xc9, 0x06, 0x0a, 0xba, 0xf9, 0x66, 0xfc, 0xf3,
	0x7c, 0x1a, 0xf8, 0xd7, 0xbf, 0x69, 0xea, 0x1c, 0x1d, 0xba, 0x7a, 0x9c, 0x1c, 0x39, 0xdc, 0xae,
	0x8d, 0xb1, 0xdb, 0x11, 0x24, 0x2f, 0xde, 0x4c, 0x78, 0x03, 0x9b, 0xf3, 0xd0, 0xbf, 0x3f, 0x69,
	0x6b, 0xa4, 0x28, 0x45, 0x55, 0xa8, 0x95, 0xf1, 0x1a, 0xb2, 0x0f, 0x6f, 0xa6, 0xb6, 0x91, 0x11,
	0x4f, 0x16, 0x0a, 0x99, 0x50, 0x71, 0x26, 0x9e, 0x33, 0x17, 0xc6, 0x5b, 0x28, 0x4e, 0xda, 0xd3,
	0xde, 0x1f, 0xdb, 0x46, 0x26, 0xa5, 0xa8, 0x62, 0xf5, 0xd3, 0xd8, 0x7d, 0x09, 0xc8, 0xf7, 0xc6,
	0x7b, 0x7d, 0xe4, 0xdf, 0x83, 0x50, 0xdb, 0x2c, 0x7b, 0x17, 0xc2, 0x7b, 0x48, 0x5e, 0x27, 0x67,
	0x79, 0xe7, 0xf6, 0xe1, 0x7f, 0xfd, 0xcb, 0xba, 0x0e, 0xca, 0x8a, 0xc7, 0x78, 0x07, 0x11, 0x39,
	0x5e, 0xff, 0xe7, 0xa3, 0x88, 0x1c, 0x22, 0x24, 0x64, 0x3e, 0x89, 0x35, 0x0a, 0xc5, 0x75, 0xf0,
	0xa3, 0xc1, 0x9a, 0x67, 0xd2, 0x76, 0x94, 0xe9, 0xec, 0xb7, 0x36, 0xf0, 0x0a, 0x52, 0xcb, 0xe6,
	0x19, 0x47, 0x66, 0x40, 0x09, 0xb9, 0x1b, 0x69, 0x70, 0x67, 0x2f, 0xf3, 0x32, 0xae, 0x0a, 0x75,
	0xc1, 0x70, 0x09, 0x6f, 0x4e, 0xa6, 0x27, 0x73, 0x90, 0x9b, 0x52, 0x54, 0xa9, 0x5a, 0xb9, 0xcb,
	0xf8, 0xea, 0x8f, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x42, 0x4a, 0x72, 0x0f, 0x88, 0x01, 0x00,
	0x00,
}
