// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chatbotdb.proto

package chatbotdbpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// User - chat user info
type User struct {
	// nickName - User's nickname
	NickName string `protobuf:"bytes,1,opt,name=nickName,proto3" json:"nickName,omitempty"`
	// userID - User's unique identifier
	UserID string `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	// userName - Username
	UserName string `protobuf:"bytes,3,opt,name=userName,proto3" json:"userName,omitempty"`
	// lastMsgID - The last msgid that has been processed
	LastMsgID            int64    `protobuf:"varint,4,opt,name=lastMsgID,proto3" json:"lastMsgID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_chatbotdb_a20efeefee58e9da, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *User) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *User) GetLastMsgID() int64 {
	if m != nil {
		return m.LastMsgID
	}
	return 0
}

// File - file info
type File struct {
	// filename - Filename
	Filename string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	// data - File data
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// fileType - File type
	FileType string `protobuf:"bytes,3,opt,name=fileType,proto3" json:"fileType,omitempty"`
	// strData - Base64 encoded file data
	StrData              string   `protobuf:"bytes,4,opt,name=strData,proto3" json:"strData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_chatbotdb_a20efeefee58e9da, []int{1}
}
func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (dst *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(dst, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *File) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *File) GetFileType() string {
	if m != nil {
		return m.FileType
	}
	return ""
}

func (m *File) GetStrData() string {
	if m != nil {
		return m.StrData
	}
	return ""
}

// Message - message
type Message struct {
	// chatID - The globally unique identifier of the message, in a format similar to userid:msgid
	ChatID string `protobuf:"bytes,1,opt,name=chatID,proto3" json:"chatID,omitempty"`
	// from - Message user
	From *User `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	// to - User receiving the message
	To *User `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	// text - Message text content
	Text string `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	// timeStamp - Time of sending a message
	TimeStamp int64 `protobuf:"varint,5,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	// msgID - User's message unique identifier
	MsgID string `protobuf:"bytes,6,opt,name=msgID,proto3" json:"msgID,omitempty"`
	// options - The options contained in the message
	Options []string `protobuf:"bytes,7,rep,name=options,proto3" json:"options,omitempty"`
	// selected - User selected option
	Selected int32 `protobuf:"varint,8,opt,name=selected,proto3" json:"selected,omitempty"`
	// file - File in the message
	File                 *File    `protobuf:"bytes,9,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_chatbotdb_a20efeefee58e9da, []int{2}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetChatID() string {
	if m != nil {
		return m.ChatID
	}
	return ""
}

func (m *Message) GetFrom() *User {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Message) GetTo() *User {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Message) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *Message) GetMsgID() string {
	if m != nil {
		return m.MsgID
	}
	return ""
}

func (m *Message) GetOptions() []string {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *Message) GetSelected() int32 {
	if m != nil {
		return m.Selected
	}
	return 0
}

func (m *Message) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "chatbotdbpb.User")
	proto.RegisterType((*File)(nil), "chatbotdbpb.File")
	proto.RegisterType((*Message)(nil), "chatbotdbpb.Message")
}

func init() { proto.RegisterFile("chatbotdb.proto", fileDescriptor_chatbotdb_a20efeefee58e9da) }

var fileDescriptor_chatbotdb_a20efeefee58e9da = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x49, 0x9a, 0xfe, 0x9b, 0x0a, 0xe2, 0x22, 0xb2, 0x88, 0x87, 0x58, 0x10, 0x7a, 0xea,
	0x41, 0x5f, 0x21, 0x08, 0x3d, 0xd4, 0xc3, 0xaa, 0x0f, 0xb0, 0x69, 0xa7, 0x75, 0x71, 0xd3, 0x0d,
	0xd9, 0x11, 0xf4, 0x2d, 0x7c, 0x64, 0x99, 0x69, 0x12, 0x7b, 0xe8, 0x6d, 0x7e, 0x33, 0x3b, 0xf9,
	0xe6, 0xfb, 0x08, 0x5c, 0x6e, 0x3e, 0x2c, 0x95, 0x81, 0xb6, 0xe5, 0xb2, 0x6e, 0x02, 0x05, 0x35,
	0xeb, 0x1b, 0x75, 0x39, 0x27, 0xc8, 0xde, 0x23, 0x36, 0xea, 0x16, 0x26, 0x07, 0xb7, 0xf9, 0x7c,
	0xb1, 0x15, 0xea, 0x24, 0x4f, 0x16, 0x53, 0xd3, 0xb3, 0xba, 0x81, 0xd1, 0x57, 0xc4, 0x66, 0x55,
	0xe8, 0x54, 0x26, 0x2d, 0xf1, 0x0e, 0x57, 0xb2, 0x33, 0x38, 0xee, 0x74, 0xac, 0xee, 0x60, 0xea,
	0x6d, 0xa4, 0x75, 0xdc, 0xaf, 0x0a, 0x9d, 0xe5, 0xc9, 0x62, 0x60, 0xfe, 0x1b, 0x73, 0x0f, 0xd9,
	0xb3, 0xf3, 0xc8, 0x5f, 0xd8, 0x39, 0x8f, 0x87, 0x13, 0xd5, 0x8e, 0x95, 0x82, 0x6c, 0x6b, 0xc9,
	0x8a, 0xe6, 0x85, 0x91, 0xba, 0x7b, 0xff, 0xf6, 0x53, 0xf7, 0x8a, 0x1d, 0x2b, 0x0d, 0xe3, 0x48,
	0x4d, 0xc1, 0x2b, 0x99, 0x8c, 0x3a, 0x9c, 0xff, 0xa6, 0x30, 0x5e, 0x63, 0x8c, 0x76, 0x2f, 0x5e,
	0xd8, 0xfe, 0xaa, 0x68, 0xf5, 0x5a, 0x52, 0x0f, 0x90, 0xed, 0x9a, 0x50, 0x89, 0xda, 0xec, 0xf1,
	0x6a, 0x79, 0x92, 0xd1, 0x92, 0x03, 0x32, 0x32, 0x56, 0xf7, 0x90, 0x52, 0x10, 0xe9, 0xb3, 0x8f,
	0x52, 0x0a, 0x7c, 0x37, 0xe1, 0x37, 0xb5, 0x47, 0x48, 0xcd, 0x69, 0x90, 0xab, 0xf0, 0x95, 0x6c,
	0x55, 0xeb, 0xe1, 0x31, 0x8d, 0xbe, 0xa1, 0xae, 0x61, 0x58, 0x49, 0x4e, 0x23, 0x59, 0x39, 0x02,
	0xfb, 0x09, 0x35, 0xb9, 0x70, 0x88, 0x7a, 0x9c, 0x0f, 0xd8, 0x4f, 0x8b, 0x9c, 0x42, 0x44, 0x8f,
	0x1b, 0xc2, 0xad, 0x9e, 0xe4, 0xc9, 0x62, 0x68, 0x7a, 0x16, 0x1f, 0xce, 0xa3, 0x9e, 0x9e, 0x39,
	0x91, 0x23, 0x37, 0x32, 0x2e, 0x47, 0xf2, 0x2b, 0x3c, 0xfd, 0x05, 0x00, 0x00, 0xff, 0xff, 0x71,
	0x01, 0x73, 0xd5, 0x1d, 0x02, 0x00, 0x00,
}
