// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usermgr.proto

package pluginusermgrpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// UpdScriptCommand - updscript command
type UpdScriptCommand struct {
	// userID - userID
	UserID string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	// userName - userName
	UserName string `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	// scriptName - script name
	ScriptName string `protobuf:"bytes,3,opt,name=scriptName,proto3" json:"scriptName,omitempty"`
	// jarvisNodeName - jarvis node name
	JarvisNodeName       string   `protobuf:"bytes,4,opt,name=jarvisNodeName,proto3" json:"jarvisNodeName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdScriptCommand) Reset()         { *m = UpdScriptCommand{} }
func (m *UpdScriptCommand) String() string { return proto.CompactTextString(m) }
func (*UpdScriptCommand) ProtoMessage()    {}
func (*UpdScriptCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_usermgr_31cae0e4645f968f, []int{0}
}
func (m *UpdScriptCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdScriptCommand.Unmarshal(m, b)
}
func (m *UpdScriptCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdScriptCommand.Marshal(b, m, deterministic)
}
func (dst *UpdScriptCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdScriptCommand.Merge(dst, src)
}
func (m *UpdScriptCommand) XXX_Size() int {
	return xxx_messageInfo_UpdScriptCommand.Size(m)
}
func (m *UpdScriptCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdScriptCommand.DiscardUnknown(m)
}

var xxx_messageInfo_UpdScriptCommand proto.InternalMessageInfo

func (m *UpdScriptCommand) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UpdScriptCommand) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UpdScriptCommand) GetScriptName() string {
	if m != nil {
		return m.ScriptName
	}
	return ""
}

func (m *UpdScriptCommand) GetJarvisNodeName() string {
	if m != nil {
		return m.JarvisNodeName
	}
	return ""
}

// UserScriptsCommand - userscripts command
type UserScriptsCommand struct {
	// userID - userID
	UserID string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	// userName - userName
	UserName string `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	// jarvisNodeName - jarvis node name
	JarvisNodeName       string   `protobuf:"bytes,3,opt,name=jarvisNodeName,proto3" json:"jarvisNodeName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserScriptsCommand) Reset()         { *m = UserScriptsCommand{} }
func (m *UserScriptsCommand) String() string { return proto.CompactTextString(m) }
func (*UserScriptsCommand) ProtoMessage()    {}
func (*UserScriptsCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_usermgr_31cae0e4645f968f, []int{1}
}
func (m *UserScriptsCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserScriptsCommand.Unmarshal(m, b)
}
func (m *UserScriptsCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserScriptsCommand.Marshal(b, m, deterministic)
}
func (dst *UserScriptsCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserScriptsCommand.Merge(dst, src)
}
func (m *UserScriptsCommand) XXX_Size() int {
	return xxx_messageInfo_UserScriptsCommand.Size(m)
}
func (m *UserScriptsCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_UserScriptsCommand.DiscardUnknown(m)
}

var xxx_messageInfo_UserScriptsCommand proto.InternalMessageInfo

func (m *UserScriptsCommand) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UserScriptsCommand) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserScriptsCommand) GetJarvisNodeName() string {
	if m != nil {
		return m.JarvisNodeName
	}
	return ""
}

// RemoveScriptCommand - rmscript command
type RemoveScriptCommand struct {
	// userID - userID
	UserID string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	// userName - userName
	UserName string `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	// scriptName - script name
	ScriptName           string   `protobuf:"bytes,3,opt,name=scriptName,proto3" json:"scriptName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveScriptCommand) Reset()         { *m = RemoveScriptCommand{} }
func (m *RemoveScriptCommand) String() string { return proto.CompactTextString(m) }
func (*RemoveScriptCommand) ProtoMessage()    {}
func (*RemoveScriptCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_usermgr_31cae0e4645f968f, []int{2}
}
func (m *RemoveScriptCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveScriptCommand.Unmarshal(m, b)
}
func (m *RemoveScriptCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveScriptCommand.Marshal(b, m, deterministic)
}
func (dst *RemoveScriptCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveScriptCommand.Merge(dst, src)
}
func (m *RemoveScriptCommand) XXX_Size() int {
	return xxx_messageInfo_RemoveScriptCommand.Size(m)
}
func (m *RemoveScriptCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveScriptCommand.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveScriptCommand proto.InternalMessageInfo

func (m *RemoveScriptCommand) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *RemoveScriptCommand) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *RemoveScriptCommand) GetScriptName() string {
	if m != nil {
		return m.ScriptName
	}
	return ""
}

// ShowScriptCommand - showscript command
type ShowScriptCommand struct {
	// userID - userID
	UserID string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	// userName - userName
	UserName string `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	// scriptName - script name
	ScriptName           string   `protobuf:"bytes,3,opt,name=scriptName,proto3" json:"scriptName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowScriptCommand) Reset()         { *m = ShowScriptCommand{} }
func (m *ShowScriptCommand) String() string { return proto.CompactTextString(m) }
func (*ShowScriptCommand) ProtoMessage()    {}
func (*ShowScriptCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_usermgr_31cae0e4645f968f, []int{3}
}
func (m *ShowScriptCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowScriptCommand.Unmarshal(m, b)
}
func (m *ShowScriptCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowScriptCommand.Marshal(b, m, deterministic)
}
func (dst *ShowScriptCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowScriptCommand.Merge(dst, src)
}
func (m *ShowScriptCommand) XXX_Size() int {
	return xxx_messageInfo_ShowScriptCommand.Size(m)
}
func (m *ShowScriptCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowScriptCommand.DiscardUnknown(m)
}

var xxx_messageInfo_ShowScriptCommand proto.InternalMessageInfo

func (m *ShowScriptCommand) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *ShowScriptCommand) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *ShowScriptCommand) GetScriptName() string {
	if m != nil {
		return m.ScriptName
	}
	return ""
}

func init() {
	proto.RegisterType((*UpdScriptCommand)(nil), "pluginusermgrpb.UpdScriptCommand")
	proto.RegisterType((*UserScriptsCommand)(nil), "pluginusermgrpb.UserScriptsCommand")
	proto.RegisterType((*RemoveScriptCommand)(nil), "pluginusermgrpb.RemoveScriptCommand")
	proto.RegisterType((*ShowScriptCommand)(nil), "pluginusermgrpb.ShowScriptCommand")
}

func init() { proto.RegisterFile("usermgr.proto", fileDescriptor_usermgr_31cae0e4645f968f) }

var fileDescriptor_usermgr_31cae0e4645f968f = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x2d, 0x4e, 0x2d,
	0xca, 0x4d, 0x2f, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2f, 0xc8, 0x29, 0x4d, 0xcf,
	0xcc, 0x83, 0x0a, 0x16, 0x24, 0x29, 0xf5, 0x31, 0x72, 0x09, 0x84, 0x16, 0xa4, 0x04, 0x27, 0x17,
	0x65, 0x16, 0x94, 0x38, 0xe7, 0xe7, 0xe6, 0x26, 0xe6, 0xa5, 0x08, 0x89, 0x71, 0xb1, 0x81, 0x54,
	0x78, 0xba, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x79, 0x42, 0x52, 0x5c, 0x1c, 0x20,
	0x96, 0x5f, 0x62, 0x6e, 0xaa, 0x04, 0x13, 0x58, 0x06, 0xce, 0x17, 0x92, 0xe3, 0xe2, 0x2a, 0x06,
	0x1b, 0x02, 0x96, 0x65, 0x06, 0xcb, 0x22, 0x89, 0x08, 0xa9, 0x71, 0xf1, 0x65, 0x25, 0x16, 0x95,
	0x65, 0x16, 0xfb, 0xe5, 0xa7, 0xa4, 0x82, 0xd5, 0xb0, 0x80, 0xd5, 0xa0, 0x89, 0x2a, 0x15, 0x70,
	0x09, 0x85, 0x16, 0xa7, 0x16, 0x41, 0x1c, 0x54, 0x4c, 0x89, 0x8b, 0x30, 0x6d, 0x64, 0xc6, 0x6a,
	0x63, 0x26, 0x97, 0x70, 0x50, 0x6a, 0x6e, 0x7e, 0x59, 0x2a, 0xcd, 0x03, 0x41, 0x29, 0x9d, 0x4b,
	0x30, 0x38, 0x23, 0xbf, 0x9c, 0xe6, 0x16, 0x25, 0xb1, 0x81, 0xa3, 0xdb, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0x1a, 0xf4, 0xcb, 0x14, 0xff, 0x01, 0x00, 0x00,
}
