// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cmdline.proto

package chatbotpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// EmptyCommand - empty command
type EmptyCommand struct {
	// cmd
	Cmd                  string   `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyCommand) Reset()         { *m = EmptyCommand{} }
func (m *EmptyCommand) String() string { return proto.CompactTextString(m) }
func (*EmptyCommand) ProtoMessage()    {}
func (*EmptyCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_cmdline_ee348534459730a3, []int{0}
}
func (m *EmptyCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyCommand.Unmarshal(m, b)
}
func (m *EmptyCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyCommand.Marshal(b, m, deterministic)
}
func (dst *EmptyCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyCommand.Merge(dst, src)
}
func (m *EmptyCommand) XXX_Size() int {
	return xxx_messageInfo_EmptyCommand.Size(m)
}
func (m *EmptyCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyCommand.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyCommand proto.InternalMessageInfo

func (m *EmptyCommand) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

func init() {
	proto.RegisterType((*EmptyCommand)(nil), "chatbotpb.EmptyCommand")
}

func init() { proto.RegisterFile("cmdline.proto", fileDescriptor_cmdline_ee348534459730a3) }

var fileDescriptor_cmdline_ee348534459730a3 = []byte{
	// 87 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xce, 0x4d, 0xc9,
	0xc9, 0xcc, 0x4b, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4c, 0xce, 0x48, 0x2c, 0x49,
	0xca, 0x2f, 0x29, 0x48, 0x52, 0x52, 0xe0, 0xe2, 0x71, 0xcd, 0x2d, 0x28, 0xa9, 0x74, 0xce, 0xcf,
	0xcd, 0x4d, 0xcc, 0x4b, 0x11, 0x12, 0xe0, 0x62, 0x4e, 0xce, 0x4d, 0x91, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x0c, 0x02, 0x31, 0x93, 0xd8, 0xc0, 0x7a, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb9,
	0x66, 0xc3, 0xb0, 0x44, 0x00, 0x00, 0x00,
}
